// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9HfuIp2rNOd_0hulj0ZrLKUAy9Nee7iQ',
    appId: '1:569215252335:web:d06ec91eca1097b5825a9a',
    messagingSenderId: '569215252335',
    projectId: 'releaf-analytics',
    authDomain: 'releaf-analytics.firebaseapp.com',
    storageBucket: 'releaf-analytics.appspot.com',
    measurementId: 'G-8Y9R0LNXRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAshARm106_UZC6d0z96MfTcPDtQVF1m0M',
    appId: '1:569215252335:android:78992c359c14ad98825a9a',
    messagingSenderId: '569215252335',
    projectId: 'releaf-analytics',
    storageBucket: 'releaf-analytics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqpUdFqHAGouHaK7PlAgK_SZxkHXw1_Hc',
    appId: '1:569215252335:ios:d8075e6ef560b85c825a9a',
    messagingSenderId: '569215252335',
    projectId: 'releaf-analytics',
    storageBucket: 'releaf-analytics.appspot.com',
    iosBundleId: 'berlin.tu.releaf',
  );

}